### ISSUE TITLE
lyra2z330 works on multiple GPUs on klausT-mod-r9

### ISSUE THREAD

**Issue by platinum4** [Minerx117/ccmineryescryptr8g#1]
Hi, can you rebuild klausT-mod-r9 in new codebase/toolset/cuda/vs so can mine lyra2z330 on rigs with more than 1 GPU.  This version is before it implemented "4-way" or "16-way" mode

**Comment by Minerx117** [comment]
thankyou @platinum4 i'll get that done asap for you
