### ISSUE TITLE
Yo nemo can you re-wrap this with CUDA10 and some more goodies

### ISSUE THREAD

**Issue by platinum4** [Minerx117/ccmineryescryptr8g#3]
https://github.com/brian112358/ccminer-bsha3/releases/tag/v1.0

**Comment by Minerx117** [comment]
@platinum4 i compiled it with cuda 10 its slower than the original release with 1% dev fee so no point with cuda 10..

cuda 9.1 is yielding better results tho.. hang tight i'll release something soon for sha3d

**Comment by platinum4** [comment]
Hell yeah, provide the miner that I need to succeed breh

**Comment by platinum4** [comment]
Driver 450.12 has CUDA11 too fool

**Comment by platinum4** [comment]
YOU GOTTA BE QUICK WHEN YOU TRYNA BE SLICK

**Comment by Minerx117** [comment]
ok not as if it matters sha3d is fpga territory

**Comment by platinum4** [comment]
my territory is making bank
